### ISSUE TITLE
第四版没第三版好用

### ISSUE THREAD

**Issue by hemingfei** [1414044032/DingDingAutoPlayCard#2]
原因是：有的手机点击了工作按钮后，无法直接点击到考情打卡，需要下滑等操作。或者点击考勤统计按钮进去后再点击打卡按钮。所以最好做成可配置的

**Comment by 1414044032** [comment]
新版的钉钉可以设置极速打卡，上下班可以直接打开即可，其他细节，并没有做相关优化，如果不能极速上班打开，可以参考下班打卡的逻辑，进行锚点的配置。第4版是在第二版的基础上封装的，只保留了基本的打卡后邮件通知功能，第三版是全部功能，所以。。。。
