### ISSUE TITLE
感谢代码，判断是否周末那里 可以判断一下是否是法定节假日或补班！

### ISSUE THREAD

**Issue by duanqichao** [1414044032/DingDingAutoPlayCard#3]
用这个接口 http://api.goseek.cn/

**Comment by 1414044032** [comment]
Dear：
       之前考虑过，这里做成配置的，用户可以根据自己的需要设置自动打卡的时间，后来发现判断节假日的网上的API大部分是个人提供的，所以这里，我只判断是否是周末，如果有需要，你可以覆盖判断是否是周末的方法来实现的打卡的时间点
