### ISSUE TITLE
请问这个钉钉打卡是不是需要一个手机一直连接电脑

### ISSUE THREAD

**Issue by banduoba** [1414044032/DingDingAutoPlayCard#4]
这个打卡是脱离手机的还是需要一个手机,安卓模拟器可以么

**Comment by cloud0435** [comment]
> 这个打卡是脱离手机的还是需要一个手机,安卓模拟器可以么

请问可以用么

**Comment by 1414044032** [comment]
安卓模拟器没研究过，这个我不清楚，你可以先试试安卓模拟器手动能打卡不！一般会对模拟器进行识别吧

**Comment by cz1980** [comment]
在安卓手机上装个Linux系统，能不能将这个Python直接放在手机上跑呢？

**Comment by 1414044032** [comment]
这个本质上是通过adb操作手机的，
