### ISSUE TITLE
关于获取屏幕尺寸，设置模拟点击位置的优化

### ISSUE THREAD

**Issue by Adam-Zhong** [1414044032/DingDingAutoPlayCard#5]
可以打开"开发者设置"的输入找到"指针位置" 即可得到点击XY坐标轴

**Comment by 1414044032** [comment]
优秀，我竟然没想到。

**Comment by Adam-Zhong** [comment]
> 优秀，我竟然没想到。

哈哈. 居然在线, 还是感谢你发明这个东西  
还有一个问题, 如何在一部电脑上同时操作多部手机?

**Comment by Adam-Zhong** [comment]
> 可以打开"开发者设置"的输入找到"指针位置" 即可得到点击XY坐标轴

![image](https://user-images.githubusercontent.com/40572216/64086339-31f6dc00-cd6a-11e9-9ccd-7ba0ba7624f1.png)

B

**Comment by 1414044032** [comment]
操作多部手机，没研究过，你可以参阅adb的命令列表研究一下，这个 说白了 还是基于adb 来操作安卓手机的

**Comment by Adam-Zhong** [comment]
> 操作多部手机，没研究过，你可以参阅adb的命令列表研究一下，这个 说白了 还是基于adb 来操作安卓手机的

好的, 我去研究一下, 有成果了跟你说一声

**Comment by 1414044032** [comment]
好嘞，啧啧，别被老板发现

**Comment by Adam-Zhong** [comment]
> 好嘞，啧啧，别被老板发现

哈哈, 整个办公室狼狈为奸, 不怕不怕, 为大家谋福利

**Comment by 1414044032** [comment]
adb命令，参阅这个：https://github.com/mzlogin/awesome-adb 。

**Comment by Adam-Zhong** [comment]
> adb命令，参阅这个：https://github.com/mzlogin/awesome-adb 。

谢谢
